name: Test Eel

on:
  push:
    branches: [master]
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest] #ubuntu-20.04, macos-latest
        python-version: [3.6, 3.7, 3.8, 3.9, '3.10']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Build a source distribution
        run: python setup.py sdist
      - name: Setup test execution environment.
        run: pip3 install -r requirements-meta.txt
      - name: Run tox tests
        run: tox -- --durations=0 --timeout=30
